import Head from 'next/head';
import Form from '../components/Form/Form';
import PostList from '../components/Post/PostList';
import { store } from '../redux/store';
import { Provider } from 'react-redux';

export default function Home() {
  return (
    <Provider store={store}>
      <div className="flex justify-center space-x-4 ">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <PostList />
        <Form />
      </div>
    </Provider>
  );
}
